### ISSUE TITLE
No drop down menu

### ISSUE THREAD

**Issue by computersarecool** [ScottyB/ac-js2#20]
Hi, I believe I have this installed just the readme says, but I am still not getting a drop down window when I type a previously-typed function:  i.e.

![screen shot 2015-04-14 at 8 48 13 pm](https://cloud.githubusercontent.com/assets/5414692/7152022/59388abe-e2e8-11e4-8976-ac0d978a5710.png)

I have in my .emacs:
````
(add-to-list 'auto-mode-alist (cons (rx ".js" eos) 'js2-mode)) 
(add-hook 'js-mode-hook 'ac-js2-mode) 
````

So I do not know what is wrong.  Any ideas?

**Comment by patapizza** [comment]
You should add `ac-js2-mode` to the `js2-mode-hook`, and not to the `js-mode-hook`:

```elisp
(add-hook 'js2-mode-hook 'ac-js2-mode) 
```
